language: java
jdk: oraclejdk8
sudo: false

before_install: chmod +x gradlew
install:
  - ""
script:
  - ./gradlew build check

cache:
  directories:
  - ~/.gradle

notifications:
  email: false
  irc:
    - "irc.esper.net#calclavia"
    - "irc.esper.net#NovaAPI"